services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jamin-phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
